version: '3.8'

services:
  app:
    image: edwinzurawik/expenses-manager
    build: .
    ports:
      - 8080:3000
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb

volumes:
  mongodbdata:
  mongodbconfig:
